<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
      $items = [
                     
						['id' => 1, 'code' => 'AF', 'country' => 'Afghanistan'],
						['id' => 2, 'code' => 'AL', 'country' => 'Albania'],
						['id' => 3, 'code' => 'DZ', 'country' => 'Algeria'],
						['id' => 4, 'code' => 'AS', 'country' => 'American Samoa',],
						['id' => 5, 'code' => 'AD', 'country' => 'Andorra',],
						['id' => 6, 'code' => 'AO', 'country' => 'Angola',],
						['id' => 7, 'code' => 'AI', 'country' => 'Anguilla',],
						['id' => 8, 'code' => 'AQ', 'country' => 'Antarctica',],
						['id' => 9, 'code' => 'AG', 'country' => 'Antigua and Barbuda',],
						['id' => 10, 'code' => 'AR', 'country' => 'Argentina',],
						['id' => 11, 'code' => 'AM', 'country' => 'Armenia',],
						['id' => 12, 'code' => 'AW', 'country' => 'Aruba',],
						['id' => 13, 'code' => 'AU', 'country' => 'Australia',],
						['id' => 14, 'code' => 'AT', 'country' => 'Austria',],
						['id' => 15, 'code' => 'AZ', 'country' => 'Azerbaijan',],
						['id' => 16, 'code' => 'BS', 'country' => 'Bahamas',],
						['id' => 17, 'code' => 'BH', 'country' => 'Bahrain',],
						['id' => 18, 'code' => 'BD', 'country' => 'Bangladesh',],
						['id' => 19, 'code' => 'BB', 'country' => 'Barbados',],
						['id' => 20, 'code' => 'BY', 'country' => 'Belarus',],
						['id' => 21, 'code' => 'BE', 'country' => 'Belgium',],
						['id' => 22, 'code' => 'BZ', 'country' => 'Belize',],
						['id' => 23, 'code' => 'BJ', 'country' => 'Benin',],
						['id' => 24, 'code' => 'BM', 'country' => 'Bermuda',],
						['id' => 25, 'code' => 'BT', 'country' => 'Bhutan',],
						['id' => 26, 'code' => 'BO', 'country' => 'Bolivia',],
						['id' => 27, 'code' => 'BA', 'country' => 'Bosnia and Herzegovina',],
						['id' => 28, 'code' => 'BW', 'country' => 'Botswana',],
						['id' => 29, 'code' => 'BV', 'country' => 'Bouvet Island',],
						['id' => 30, 'code' => 'BR', 'country' => 'Brazil',],
						['id' => 31, 'code' => 'BQ', 'country' => 'British Antarctic Territory',],
						['id' => 32, 'code' => 'IO', 'country' => 'British Indian Ocean Territory',],
						['id' => 33, 'code' => 'VG', 'country' => 'British Virgin Islands',],
						['id' => 34, 'code' => 'BN', 'country' => 'Brunei',],
						['id' => 35, 'code' => 'BG', 'country' => 'Bulgaria',],
						['id' => 36, 'code' => 'BF', 'country' => 'Burkina Faso',],
						['id' => 37, 'code' => 'BI', 'country' => 'Burundi',],
						['id' => 38, 'code' => 'KH', 'country' => 'Cambodia',],
						['id' => 39, 'code' => 'CM', 'country' => 'Cameroon',],
						['id' => 40, 'code' => 'CA', 'country' => 'Canada',],
						['id' => 41, 'code' => 'CT', 'country' => 'Canton and Enderbury Islands',],
						['id' => 42, 'code' => 'CV', 'country' => 'Cape Verde',],
						['id' => 43, 'code' => 'KY', 'country' => 'Cayman Islands',],
						['id' => 44, 'code' => 'CF', 'country' => 'Central African Republic',],
						['id' => 45, 'code' => 'TD', 'country' => 'Chad',],
						['id' => 46, 'code' => 'CL', 'country' => 'Chile',],
						['id' => 47, 'code' => 'CN', 'country' => 'China',],
						['id' => 48, 'code' => 'CX', 'country' => 'Christmas Island',],
						['id' => 49, 'code' => 'CC', 'country' => 'Cocos [Keeling] Islands',],
						['id' => 50, 'code' => 'CO', 'country' => 'Colombia',],
						['id' => 51, 'code' => 'KM', 'country' => 'Comoros',],
						['id' => 52, 'code' => 'CG', 'country' => 'Congo - Brazzaville',],
						['id' => 53, 'code' => 'CD', 'country' => 'Congo - Kinshasa',],
						['id' => 54, 'code' => 'CK', 'country' => 'Cook Islands',],
						['id' => 55, 'code' => 'CR', 'country' => 'Costa Rica',],
						['id' => 56, 'code' => 'HR', 'country' => 'Croatia',],
						['id' => 57, 'code' => 'CU', 'country' => 'Cuba',],
						['id' => 58, 'code' => 'CY', 'country' => 'Cyprus',],
						['id' => 59, 'code' => 'CZ', 'country' => 'Czech Republic',],
						['id' => 60, 'code' => 'CI', 'country' => 'Côte d’Ivoire',],
						['id' => 61, 'code' => 'DK', 'country' => 'Denmark',],
						['id' => 62, 'code' => 'DJ', 'country' => 'Djibouti',],
						['id' => 63, 'code' => 'DM', 'country' => 'Dominica',],
						['id' => 64, 'code' => 'DO', 'country' => 'Dominican Republic',],
						['id' => 65, 'code' => 'NQ', 'country' => 'Dronning Maud Land',],
						['id' => 66, 'code' => 'DD', 'country' => 'East Germany',],
						['id' => 67, 'code' => 'EC', 'country' => 'Ecuador',],
						['id' => 68, 'code' => 'EG', 'country' => 'Egypt',],
						['id' => 69, 'code' => 'SV', 'country' => 'El Salvador',],
						['id' => 70, 'code' => 'GQ', 'country' => 'Equatorial Guinea',],
						['id' => 71, 'code' => 'ER', 'country' => 'Eritrea',],
						['id' => 72, 'code' => 'EE', 'country' => 'Estonia',],
						['id' => 73, 'code' => 'ET', 'country' => 'Ethiopia',],
						['id' => 74, 'code' => 'FK', 'country' => 'Falkland Islands',],
						['id' => 75, 'code' => 'FO', 'country' => 'Faroe Islands',],
						['id' => 76, 'code' => 'FJ', 'country' => 'Fiji',],
						['id' => 77, 'code' => 'FI', 'country' => 'Finland',],
						['id' => 78, 'code' => 'FR', 'country' => 'France',],
						['id' => 79, 'code' => 'GF', 'country' => 'French Guiana',],
						['id' => 80, 'code' => 'PF', 'country' => 'French Polynesia',],
						['id' => 81, 'code' => 'TF', 'country' => 'French Southern Territories',],
						['id' => 82, 'code' => 'FQ', 'country' => 'French Southern and Antarctic Territories',],
						['id' => 83, 'code' => 'GA', 'country' => 'Gabon',],
						['id' => 84, 'code' => 'GM', 'country' => 'Gambia',],
						['id' => 85, 'code' => 'GE', 'country' => 'Georgia',],
						['id' => 86, 'code' => 'DE', 'country' => 'Germany',],
						['id' => 87, 'code' => 'GH', 'country' => 'Ghana',],
						['id' => 88, 'code' => 'GI', 'country' => 'Gibraltar',],
						['id' => 89, 'code' => 'GR', 'country' => 'Greece',],
						['id' => 90, 'code' => 'GL', 'country' => 'Greenland',],
						['id' => 91, 'code' => 'GD', 'country' => 'Grenada',],
						['id' => 92, 'code' => 'GP', 'country' => 'Guadeloupe',],
						['id' => 93, 'code' => 'GU', 'country' => 'Guam',],
						['id' => 94, 'code' => 'GT', 'country' => 'Guatemala',],
						['id' => 95, 'code' => 'GG', 'country' => 'Guernsey',],
						['id' => 96, 'code' => 'GN', 'country' => 'Guinea',],
						['id' => 97, 'code' => 'GW', 'country' => 'Guinea-Bissau',],
						['id' => 98, 'code' => 'GY', 'country' => 'Guyana',],
						['id' => 99, 'code' => 'HT', 'country' => 'Haiti',],
						['id' => 100, 'code' => 'HM', 'country' => 'Heard Island and McDonald Islands',],
						['id' => 101, 'code' => 'HN', 'country' => 'Honduras',],
						['id' => 102, 'code' => 'HK', 'country' => 'Hong Kong SAR China',],
						['id' => 103, 'code' => 'HU', 'country' => 'Hungary',],
						['id' => 104, 'code' => 'IS', 'country' => 'Iceland',],
						['id' => 105, 'code' => 'IN', 'country' => 'India',],
						['id' => 106, 'code' => 'ID', 'country' => 'Indonesia',],
						['id' => 107, 'code' => 'IR', 'country' => 'Iran',],
						['id' => 108, 'code' => 'IQ', 'country' => 'Iraq',],
						['id' => 109, 'code' => 'IE', 'country' => 'Ireland',],
						['id' => 110, 'code' => 'IM', 'country' => 'Isle of Man',],
						['id' => 111, 'code' => 'IL', 'country' => 'Israel',],
						['id' => 112, 'code' => 'IT', 'country' => 'Italy',],
						['id' => 113, 'code' => 'JM', 'country' => 'Jamaica',],
						['id' => 114, 'code' => 'JP', 'country' => 'Japan',],
						['id' => 115, 'code' => 'JE', 'country' => 'Jersey',],
						['id' => 116, 'code' => 'JT', 'country' => 'Johnston Island',],
						['id' => 117, 'code' => 'JO', 'country' => 'Jordan',],
						['id' => 118, 'code' => 'KZ', 'country' => 'Kazakhstan',],
						['id' => 119, 'code' => 'KE', 'country' => 'Kenya',],
						['id' => 120, 'code' => 'KI', 'country' => 'Kiribati',],
						['id' => 121, 'code' => 'KW', 'country' => 'Kuwait',],
						['id' => 122, 'code' => 'KG', 'country' => 'Kyrgyzstan',],
						['id' => 123, 'code' => 'LA', 'country' => 'Laos',],
						['id' => 124, 'code' => 'LV', 'country' => 'Latvia',],
						['id' => 125, 'code' => 'LB', 'country' => 'Lebanon',],
						['id' => 126, 'code' => 'LS', 'country' => 'Lesotho',],
						['id' => 127, 'code' => 'LR', 'country' => 'Liberia',],
						['id' => 128, 'code' => 'LY', 'country' => 'Libya',],
						['id' => 129, 'code' => 'LI', 'country' => 'Liechtenstein',],
						['id' => 130, 'code' => 'LT', 'country' => 'Lithuania',],
						['id' => 131, 'code' => 'LU', 'country' => 'Luxembourg',],
						['id' => 132, 'code' => 'MO', 'country' => 'Macau SAR China',],
						['id' => 133, 'code' => 'MK', 'country' => 'Macedonia',],
						['id' => 134, 'code' => 'MG', 'country' => 'Madagascar',],
						['id' => 135, 'code' => 'MW', 'country' => 'Malawi',],
						['id' => 136, 'code' => 'MY', 'country' => 'Malaysia',],
						['id' => 137, 'code' => 'MV', 'country' => 'Maldives',],
						['id' => 138, 'code' => 'ML', 'country' => 'Mali',],
						['id' => 139, 'code' => 'MT', 'country' => 'Malta',],
						['id' => 140, 'code' => 'MH', 'country' => 'Marshall Islands',],
						['id' => 141, 'code' => 'MQ', 'country' => 'Martinique',],
						['id' => 142, 'code' => 'MR', 'country' => 'Mauritania',],
						['id' => 143, 'code' => 'MU', 'country' => 'Mauritius',],
						['id' => 144, 'code' => 'YT', 'country' => 'Mayotte',],
						['id' => 145, 'code' => 'FX', 'country' => 'Metropolitan France',],
						['id' => 146, 'code' => 'MX', 'country' => 'Mexico',],
						['id' => 147, 'code' => 'FM', 'country' => 'Micronesia',],
						['id' => 148, 'code' => 'MI', 'country' => 'Midway Islands',],
						['id' => 149, 'code' => 'MD', 'country' => 'Moldova',],
						['id' => 150, 'code' => 'MC', 'country' => 'Monaco',],
						['id' => 151, 'code' => 'MN', 'country' => 'Mongolia',],
						['id' => 152, 'code' => 'ME', 'country' => 'Montenegro',],
						['id' => 153, 'code' => 'MS', 'country' => 'Montserrat',],
						['id' => 154, 'code' => 'MA', 'country' => 'Morocco',],
						['id' => 155, 'code' => 'MZ', 'country' => 'Mozambique',],
						['id' => 156, 'code' => 'MM', 'country' => 'Myanmar [Burma]',],
						['id' => 157, 'code' => 'NA', 'country' => 'Namibia',],
						['id' => 158, 'code' => 'NR', 'country' => 'Nauru',],
						['id' => 159, 'code' => 'NP', 'country' => 'Nepal',],
						['id' => 160, 'code' => 'NL', 'country' => 'Netherlands',],
						['id' => 161, 'code' => 'AN', 'country' => 'Netherlands Antilles',],
						['id' => 162, 'code' => 'NT', 'country' => 'Neutral Zone',],
						['id' => 163, 'code' => 'NC', 'country' => 'New Caledonia',],
						['id' => 164, 'code' => 'NZ', 'country' => 'New Zealand',],
						['id' => 165, 'code' => 'NI', 'country' => 'Nicaragua',],
						['id' => 166, 'code' => 'NE', 'country' => 'Niger',],
						['id' => 167, 'code' => 'NG', 'country' => 'Nigeria',],
						['id' => 168, 'code' => 'NU', 'country' => 'Niue',],
						['id' => 169, 'code' => 'NF', 'country' => 'Norfolk Island',],
						['id' => 170, 'code' => 'KP', 'country' => 'North Korea',],
						['id' => 171, 'code' => 'VD', 'country' => 'North Vietnam',],
						['id' => 172, 'code' => 'MP', 'country' => 'Northern Mariana Islands',],
						['id' => 173, 'code' => 'NO', 'country' => 'Norway',],
						['id' => 174, 'code' => 'OM', 'country' => 'Oman',],
						['id' => 175, 'code' => 'PC', 'country' => 'Pacific Islands Trust Territory',],
						['id' => 176, 'code' => 'PK', 'country' => 'Pakistan',],
						['id' => 177, 'code' => 'PW', 'country' => 'Palau',],
						['id' => 178, 'code' => 'PS', 'country' => 'Palestinian Territories',],
						['id' => 179, 'code' => 'PA', 'country' => 'Panama',],
						['id' => 180, 'code' => 'PZ', 'country' => 'Panama Canal Zone',],
						['id' => 181, 'code' => 'PG', 'country' => 'Papua New Guinea',],
						['id' => 182, 'code' => 'PY', 'country' => 'Paraguay',],
						['id' => 183, 'code' => 'YD', 'country' => 'People\'s Democratic Republic of Yemen',],
						['id' => 184, 'code' => 'PE', 'country' => 'Peru',],
						['id' => 185, 'code' => 'PH', 'country' => 'Philippines',],
						['id' => 186, 'code' => 'PN', 'country' => 'Pitcairn Islands',],
						['id' => 187, 'code' => 'PL', 'country' => 'Poland',],
						['id' => 188, 'code' => 'PT', 'country' => 'Portugal',],
						['id' => 189, 'code' => 'PR', 'country' => 'Puerto Rico',],
						['id' => 190, 'code' => 'QA', 'country' => 'Qatar',],
						['id' => 191, 'code' => 'RO', 'country' => 'Romania',],
						['id' => 192, 'code' => 'RU', 'country' => 'Russia',],
						['id' => 193, 'code' => 'RW', 'country' => 'Rwanda',],
						['id' => 194, 'code' => 'RE', 'country' => 'Réunion',],
						['id' => 195, 'code' => 'BL', 'country' => 'Saint Barthélemy',],
						['id' => 196, 'code' => 'SH', 'country' => 'Saint Helena',],
						['id' => 197, 'code' => 'KN', 'country' => 'Saint Kitts and Nevis',],
						['id' => 198, 'code' => 'LC', 'country' => 'Saint Lucia',],
						['id' => 199, 'code' => 'MF', 'country' => 'Saint Martin',],
						['id' => 200, 'code' => 'PM', 'country' => 'Saint Pierre and Miquelon',],
						['id' => 201, 'code' => 'VC', 'country' => 'Saint Vincent and the Grenadines',],
						['id' => 202, 'code' => 'WS', 'country' => 'Samoa',],
						['id' => 203, 'code' => 'SM', 'country' => 'San Marino',],
						['id' => 204, 'code' => 'SA', 'country' => 'Saudi Arabia',],
						['id' => 205, 'code' => 'SN', 'country' => 'Senegal',],
						['id' => 206, 'code' => 'RS', 'country' => 'Serbia',],
						['id' => 207, 'code' => 'CS', 'country' => 'Serbia and Montenegro',],
						['id' => 208, 'code' => 'SC', 'country' => 'Seychelles',],
						['id' => 209, 'code' => 'SL', 'country' => 'Sierra Leone',],
						['id' => 210, 'code' => 'SG', 'country' => 'Singapore',],
						['id' => 211, 'code' => 'SK', 'country' => 'Slovakia',],
						['id' => 212, 'code' => 'SI', 'country' => 'Slovenia',],
						['id' => 213, 'code' => 'SB', 'country' => 'Solomon Islands',],
						['id' => 214, 'code' => 'SO', 'country' => 'Somalia',],
						['id' => 215, 'code' => 'ZA', 'country' => 'South Africa',],
						['id' => 216, 'code' => 'GS', 'country' => 'South Georgia and the South Sandwich Islands',],
						['id' => 217, 'code' => 'KR', 'country' => 'South Korea',],
						['id' => 218, 'code' => 'ES', 'country' => 'Spain',],
						['id' => 219, 'code' => 'LK', 'country' => 'Sri Lanka',],
						['id' => 220, 'code' => 'SD', 'country' => 'Sudan',],
						['id' => 221, 'code' => 'SR', 'country' => 'Suriname',],
						['id' => 222, 'code' => 'SJ', 'country' => 'Svalbard and Jan Mayen',],
						['id' => 223, 'code' => 'SZ', 'country' => 'Swaziland',],
						['id' => 224, 'code' => 'SE', 'country' => 'Sweden',],
						['id' => 225, 'code' => 'CH', 'country' => 'Switzerland',],
						['id' => 226, 'code' => 'SY', 'country' => 'Syria',],
						['id' => 227, 'code' => 'ST', 'country' => 'São Tomé and Príncipe',],
						['id' => 228, 'code' => 'TW', 'country' => 'Taiwan',],
						['id' => 229, 'code' => 'TJ', 'country' => 'Tajikistan',],
						['id' => 230, 'code' => 'TZ', 'country' => 'Tanzania',],
						['id' => 231, 'code' => 'TH', 'country' => 'Thailand',],
						['id' => 232, 'code' => 'TL', 'country' => 'Timor-Leste',],
						['id' => 233, 'code' => 'TG', 'country' => 'Togo',],
						['id' => 234, 'code' => 'TK', 'country' => 'Tokelau',],
						['id' => 235, 'code' => 'TO', 'country' => 'Tonga',],
						['id' => 236, 'code' => 'TT', 'country' => 'Trinidad and Tobago',],
						['id' => 237, 'code' => 'TN', 'country' => 'Tunisia',],
						['id' => 238, 'code' => 'TR', 'country' => 'Turkey',],
						['id' => 239, 'code' => 'TM', 'country' => 'Turkmenistan',],
						['id' => 240, 'code' => 'TC', 'country' => 'Turks and Caicos Islands',],
						['id' => 241, 'code' => 'TV', 'country' => 'Tuvalu',],
						['id' => 242, 'code' => 'UM', 'country' => 'U.S. Minor Outlying Islands',],
						['id' => 243, 'code' => 'PU', 'country' => 'U.S. Miscellaneous Pacific Islands',],
						['id' => 244, 'code' => 'VI', 'country' => 'U.S. Virgin Islands',],
						['id' => 245, 'code' => 'UG', 'country' => 'Uganda',],
						['id' => 246, 'code' => 'UA', 'country' => 'Ukraine',],
						['id' => 247, 'code' => 'SU', 'country' => 'Union of Soviet Socialist Republics',],
						['id' => 248, 'code' => 'AE', 'country' => 'United Arab Emirates',],
						['id' => 249, 'code' => 'GB', 'country' => 'United Kingdom',],
						['id' => 250, 'code' => 'US', 'country' => 'United States',],
						['id' => 251, 'code' => 'ZZ', 'country' => 'Unknown or Invalid Region',],
						['id' => 252, 'code' => 'UY', 'country' => 'Uruguay',],
						['id' => 253, 'code' => 'UZ', 'country' => 'Uzbekistan',],
						['id' => 254, 'code' => 'VU', 'country' => 'Vanuatu',],
						['id' => 255, 'code' => 'VA', 'country' => 'Vatican City',],
						['id' => 256, 'code' => 'VE', 'country' => 'Venezuela',],
						['id' => 257, 'code' => 'VN', 'country' => 'Vietnam',],
						['id' => 258, 'code' => 'WK', 'country' => 'Wake Island',],
						['id' => 259, 'code' => 'WF', 'country' => 'Wallis and Futuna',],
						['id' => 260, 'code' => 'EH', 'country' => 'Western Sahara',],
						['id' => 261, 'code' => 'YE', 'country' => 'Yemen',],
						['id' => 262, 'code' => 'ZM', 'country' => 'Zambia',],
						['id' => 263, 'code' => 'ZW', 'country' => 'Zimbabwe',],
						['id' => 264, 'code' => 'AX', 'country' => 'Åland Islands',], 
				];
        
	
		foreach($items as $item){
			 DB::table('countries')->insert([
					"country"=>$item["country"],
					"code"=>$item["code"],
				]);  
			 
		}
    }
}
